### ISSUE TITLE
Move to reworkcss org?

### ISSUE THREAD

**Issue by necolas** [reworkcss/rework-npm#12]
This would be a really good "official" plugin.

**Comment by conradz** [comment]
Sorry I forgot about this; I would be OK with this if everyone else is.

@jonathanong @lydell @bclinkinbeard @visionmedia is everyone OK with this?

**Comment by tj** [comment]
SGTM

**Comment by bclinkinbeard** [comment]
+1, bring it over as 1.0 :)

**Comment by lydell** [comment]
Sure, go ahead!

**Comment by conradz** [comment]
Done, moved to reworkcss/rework-npm! 1.0 release coming shortly, will add owners on npm.
