### ISSUE TITLE
Implement a command line interface.

### ISSUE THREAD

**Issue by Siilwyn** [reworkcss/rework-npm#20]
By supporting a command line interface this package could be directly used with npm scripts.
What do you think of the idea?

**Comment by conradz** [comment]
There already is one: https://github.com/sethvincent/rework-npm-cli. Often you will want to use other rework plugins along with this, which is very difficult with a CLI script.

**Comment by Siilwyn** [comment]
Yes I saw that one but I figured having CLI functionality on the original package is much better for the following reasons:
1. Having less dependencies.  
   _In this case three less._
2. Being up to date.  
   _Who knows what the future holds._
3. Not having to rely on small packages.  
   _With only two maintainers the chances of an abandoned package are bigger._
4. Not using 'poor' packages.  
   _The rework-npm-cli package depends on a deprecated package. Doubts about the quality._

Well I hope I convinced you, I don't see any negative consequences to implementing a CLI apart from not being used much because people combine it with other rework plugins?
Let's say you still wouldn't find it worth your time to implement would you accept a pull request implementing it?
