### ISSUE TITLE
Declaring v1.0.0

### ISSUE THREAD

**Issue by bclinkinbeard** [reworkcss/rework-npm#8]
So, this is kind of becoming a personal mission of mine, but what would you think about declaring a v1? The traditional criteria (stated if not practiced) has been if it's being used in production it's v1+. Coupled with npm's new ^ behavior, it would be great to be able to specify `"rework-npm": "^1.0.0"` and know any new, non-breaking hotness would be fetched on future installs.

Thoughts?

**Comment by ben-ng** [comment]
+1

**Comment by techwraith** [comment]
:+1:

**Comment by conradz** [comment]
Definitely should do this, but I think we need to wait for the `css-parse` to release v2.0.0, since the current version breaks with `css-parse` master.

**Comment by bclinkinbeard** [comment]
Ah OK, cool. Will that cause the API of rework-npm to change?

**Comment by conradz** [comment]
Not sure yet, although it could be possible.

**Comment by conradz** [comment]
Should also get #10 taken care of before a 1.0.

**Comment by conradz** [comment]
OK, after moving to the reworkcss org and some breaking changes, I think this is ready to go.

Major changes:
- Dropped the `dir` option, always use directory from `position.source` in the AST (see #10)
- Search the `alias` option for aliased directories when importing (see #15)
- Never apply the `alias` config for relative imports (e.g. `@import "./file";`)

Please test and provide feedback! /cc @bclinkinbeard @necolas

**Comment by necolas** [comment]
Looks good to me! A couple of quick tests behaved as I expected.

**Comment by conradz** [comment]
Released [v1.0.0](https://github.com/reworkcss/rework-npm/releases/tag/v1.0.0)!
